import { useEffect, useMemo, useRef, useState } from 'react'
import { AreaChart, Area, ResponsiveContainer, XAxis, Tooltip } from 'recharts'
import { ArrowLeft, BarChart3, CalendarDays, Check, ChevronRight, CirclePlus, CreditCard, Database, Download, Home, List, Moon, Pencil, Search, Settings, Sun, Trash2, Upload, WalletCards, X } from 'lucide-react'
import type { InstallmentItem, ItemFormData, Tab } from './types'
import { emptyForm, formatWon, formFromItem, itemFromForm, localDate, monthKey, monthPaid, monthScheduled, nextPayment, paidAmount, progress, remainingAmount } from './utils'
import { sampleItems } from './sample'

const DATA_KEY = 'installment-tracker-data'
const DARK_KEY = 'installment-tracker-settings'
const categories = ['전자기기', '생활가전', '가구', '자동차', '여행', '교육', '병원', '쇼핑', '기타']

function loadItems(): InstallmentItem[] {
  try { const stored = localStorage.getItem(DATA_KEY); return stored ? JSON.parse(stored) : sampleItems() } catch { return sampleItems() }
}

export default function App() {
  const [items, setItems] = useState<InstallmentItem[]>(loadItems)
  const [tab, setTab] = useState<Tab>('home')
  const [dark, setDark] = useState(() => JSON.parse(localStorage.getItem(DARK_KEY) || '{"dark":false}').dark)
  const [modal, setModal] = useState<'form' | 'detail' | null>(null)
  const [selected, setSelected] = useState<InstallmentItem | null>(null)
  const [form, setForm] = useState<ItemFormData>(emptyForm)
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState<'active' | 'completed' | 'all'>('active')
  const fileRef = useRef<HTMLInputElement>(null)

  useEffect(() => { localStorage.setItem(DATA_KEY, JSON.stringify(items)) }, [items])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem(DARK_KEY, JSON.stringify({ dark })) }, [dark])

  const active = items.filter(i => i.status === 'active')
  const remaining = active.reduce((sum, i) => sum + remainingAmount(i), 0)
  const scheduled = monthScheduled(items)
  const paidThisMonth = monthPaid(items)
  const visible = items.filter(i => (filter === 'all' || i.status === filter) && [i.title, i.paymentMethod, i.merchant, i.memo, i.category].join(' ').toLowerCase().includes(search.toLowerCase()))

  function openAdd() { setSelected(null); setForm(emptyForm()); setModal('form') }
  function openDetail(item: InstallmentItem) { setSelected(item); setModal('detail') }
  function openEdit(item: InstallmentItem) { setSelected(item); setForm(formFromItem(item)); setModal('form') }
  function save(e: React.FormEvent) {
    e.preventDefault()
    const next = itemFromForm(form, selected || undefined)
    setItems(prev => selected ? prev.map(i => i.id === selected.id ? next : i) : [next, ...prev])
    setSelected(next); setModal('detail')
  }
  function markNext(item: InstallmentItem, undo = false) {
    const payments = item.payments.map(p => ({ ...p }))
    if (undo) { const p = [...payments].reverse().find(p => p.status === 'paid'); if (p) { p.status = 'scheduled'; delete p.paidAt } }
    else { const p = payments.find(p => p.status === 'scheduled'); if (p) { p.status = 'paid'; p.paidAt = new Date().toISOString() } }
    const paidCount = payments.filter(p => p.status === 'paid').length
    const status = paidCount === item.installmentMonths ? 'completed' as const : 'active' as const
    const updated = { ...item, payments, paidCount, status, updatedAt: new Date().toISOString(), ...(status === 'completed' ? { completedAt: new Date().toISOString() } : { completedAt: undefined }) }
    setItems(prev => prev.map(i => i.id === item.id ? updated : i)); setSelected(updated)
  }
  function deleteItem(item: InstallmentItem) { if (confirm('이 할부 내역을 삭제하시겠습니까?\n삭제한 데이터는 복구할 수 없습니다.')) { setItems(prev => prev.filter(i => i.id !== item.id)); setModal(null) } }
  function exportData() { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), items }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `installment-tracker-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href) }
  function importData(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); const incoming = Array.isArray(parsed) ? parsed : parsed.items; if (!Array.isArray(incoming)) throw new Error(); if (confirm('현재 저장된 데이터가 불러온 데이터로 교체됩니다. 계속하시겠습니까?')) setItems(incoming) } catch { alert('올바른 할부 기록장 백업 파일이 아닙니다.') } }; reader.readAsText(file); e.target.value = '' }

  return <div className="mx-auto min-h-screen max-w-[480px] overflow-x-hidden bg-[#f8f7fb] shadow-2xl dark:bg-[#15141b] dark:text-white">
    <main className="safe-bottom min-h-screen">
      {tab === 'home' && <HomeView active={active} scheduled={scheduled} paid={paidThisMonth} remaining={remaining} onOpen={openDetail} onAdd={openAdd} />}
      {tab === 'list' && <ListView items={visible} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} onOpen={openDetail} />}
      {tab === 'stats' && <StatsView items={items} remaining={remaining} />}
      {tab === 'settings' && <SettingsView dark={dark} setDark={setDark} exportData={exportData} importClick={() => fileRef.current?.click()} clear={() => { if(confirm('모든 데이터를 초기화하시겠습니까?')) setItems([]) }} />}
    </main>
    <input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={importData} />
    <Nav tab={tab} setTab={setTab} onAdd={openAdd} />
    {modal === 'form' && <FormModal form={form} setForm={setForm} onClose={() => setModal(null)} onSave={save} editing={!!selected} />}
    {modal === 'detail' && selected && <DetailModal item={selected} onClose={() => setModal(null)} onEdit={() => openEdit(selected)} onPay={() => markNext(selected)} onUndo={() => markNext(selected, true)} onDelete={() => deleteItem(selected)} />}
  </div>
}

function Header({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <header className="flex items-end justify-between px-5 pb-5 pt-8"><div>{eyebrow && <p className="mb-1 text-sm font-semibold text-[#7663dc]">{eyebrow}</p>}<h1 className="text-[28px] font-extrabold tracking-[-1.2px]">{title}</h1></div>{action}</header> }

function HomeView({ active, scheduled, paid, remaining, onOpen, onAdd }: { active: InstallmentItem[]; scheduled: number; paid: number; remaining: number; onOpen: (i: InstallmentItem) => void; onAdd: () => void }) {
  const now = new Date(); const month = `${now.getFullYear()}년 ${now.getMonth()+1}월`
  return <><Header eyebrow={month} title="할부 기록장" action={<button onClick={onAdd} aria-label="할부 추가" className="grid h-11 w-11 place-items-center rounded-2xl bg-[#7057e8] text-white shadow-lg shadow-violet-200 dark:shadow-none"><CirclePlus /></button>} />
    <section className="px-5"><div className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#7057e8] to-[#9a75ef] p-5 text-white shadow-xl shadow-violet-200/60 dark:shadow-none"><div className="absolute -right-8 -top-10 h-36 w-36 rounded-full border-[24px] border-white/10"/><p className="text-sm font-semibold text-white/75">이번 달 납부 예정</p><p className="mt-1 text-[30px] font-extrabold tracking-tight">{formatWon(scheduled)}</p><div className="mt-5 flex gap-6 border-t border-white/20 pt-4"><div><p className="text-xs text-white/65">납부 완료</p><p className="mt-1 font-bold">{formatWon(paid)}</p></div><div><p className="text-xs text-white/65">남은 예정</p><p className="mt-1 font-bold">{formatWon(Math.max(0, scheduled-paid))}</p></div></div></div>
      <div className="mt-3 grid grid-cols-2 gap-3"><Summary icon={<WalletCards size={19}/>} label="전체 남은 금액" value={formatWon(remaining)} /><Summary icon={<CreditCard size={19}/>} label="진행 중인 할부" value={`${active.length}건`} /></div>
    </section>
    <section className="mt-7"><div className="mb-3 flex items-center justify-between px-5"><h2 className="text-lg font-extrabold">진행 중인 할부</h2><span className="text-xs font-semibold text-gray-400">결제일 순</span></div><div className="space-y-3 px-5">{active.length ? [...active].sort((a,b) => (nextPayment(a)?.scheduledDate || '').localeCompare(nextPayment(b)?.scheduledDate || '')).map(item => <ItemCard key={item.id} item={item} onClick={() => onOpen(item)} />) : <Empty onAdd={onAdd} />}</div></section></>
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-gray-100 bg-white p-4 dark:border-white/5 dark:bg-[#211f29]"><div className="mb-3 text-[#7057e8]">{icon}</div><p className="text-xs text-gray-400">{label}</p><p className="mt-1 truncate text-base font-extrabold">{value}</p></div> }
function ItemCard({ item, onClick }: { item: InstallmentItem; onClick: () => void }) { const next = nextPayment(item); return <button onClick={onClick} className="w-full rounded-[22px] border border-gray-100 bg-white p-4 text-left transition active:scale-[.98] dark:border-white/5 dark:bg-[#211f29]"><div className="flex items-start justify-between"><div className="min-w-0"><p className="truncate font-extrabold">{item.title}</p><p className="mt-1 text-xs text-gray-400">{item.paymentMethod || item.category}</p></div><ChevronRight size={18} className="text-gray-300"/></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-gray-400">월 납부 금액</p><p className="mt-0.5 text-lg font-extrabold">{formatWon(item.payments[0]?.amount || 0)}</p></div><div className="text-right"><p className="text-xs font-semibold text-[#7057e8]">{item.paidCount} / {item.installmentMonths}회</p><p className="mt-1 text-xs text-gray-400">{next ? `${localDate(next.scheduledDate)} 예정` : '납부 완료'}</p></div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-gray-100 dark:bg-white/10"><div className="h-full rounded-full bg-[#7057e8]" style={{ width: `${progress(item)}%` }}/></div></button> }
function Empty({ onAdd }: { onAdd: () => void }) { return <div className="rounded-[22px] border border-dashed border-gray-200 py-12 text-center dark:border-white/10"><CreditCard className="mx-auto text-gray-300" size={32}/><p className="mt-3 text-sm font-bold text-gray-400">등록된 할부가 없어요</p><button onClick={onAdd} className="mt-3 text-sm font-bold text-[#7057e8]">첫 할부 등록하기</button></div> }

function ListView({ items, search, setSearch, filter, setFilter, onOpen }: { items: InstallmentItem[]; search: string; setSearch: (v:string)=>void; filter: 'active'|'completed'|'all'; setFilter:(v:'active'|'completed'|'all')=>void; onOpen:(i:InstallmentItem)=>void }) { return <><Header eyebrow="내역 관리" title="모든 할부"/><div className="px-5"><div className="flex h-12 items-center gap-2 rounded-2xl bg-white px-4 dark:bg-[#211f29]"><Search size={18} className="text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="품목, 카드사, 구매처 검색" className="w-full bg-transparent text-sm outline-none"/></div><div className="hide-scroll mt-3 flex gap-2 overflow-x-auto">{(['active','completed','all'] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${filter===f?'bg-[#7057e8] text-white':'bg-white text-gray-500 dark:bg-[#211f29]'}`}>{f==='active'?'진행 중':f==='completed'?'완료':'전체'}</button>)}</div><div className="mt-5 space-y-3">{items.length ? items.map(i=><ItemCard key={i.id} item={i} onClick={()=>onOpen(i)}/>) : <p className="py-16 text-center text-sm text-gray-400">조건에 맞는 내역이 없어요.</p>}</div></div></> }

function StatsView({ items, remaining }: { items: InstallmentItem[]; remaining: number }) { const data = useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()+i);const key=monthKey(d);return {name:`${d.getMonth()+1}월`, amount:monthScheduled(items,key)}}),[items]); const category = Object.entries(items.filter(i=>i.status==='active').reduce<Record<string,number>>((a,i)=>{a[i.category]=(a[i.category]||0)+remainingAmount(i);return a},{})).sort((a,b)=>b[1]-a[1]); return <><Header eyebrow="소비 흐름" title="할부 통계"/><div className="space-y-4 px-5"><div className="rounded-[24px] bg-white p-5 dark:bg-[#211f29]"><p className="text-sm text-gray-400">전체 남은 할부 금액</p><p className="mt-1 text-2xl font-extrabold">{formatWon(remaining)}</p><div className="mt-6 h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7057e8" stopOpacity={.35}/><stop offset="100%" stopColor="#7057e8" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#999'}}/><Tooltip formatter={(v)=>formatWon(Number(v))}/><Area type="monotone" dataKey="amount" stroke="#7057e8" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></div><div className="rounded-[24px] bg-white p-5 dark:bg-[#211f29]"><h2 className="font-extrabold">카테고리별 잔액</h2><div className="mt-4 space-y-4">{category.map(([name,value])=><div key={name}><div className="mb-1.5 flex justify-between text-sm"><span>{name}</span><b>{formatWon(value)}</b></div><div className="h-2 rounded-full bg-gray-100 dark:bg-white/10"><div className="h-full rounded-full bg-[#8a73e8]" style={{width:`${remaining?value/remaining*100:0}%`}}/></div></div>)}{!category.length&&<p className="text-sm text-gray-400">표시할 데이터가 없어요.</p>}</div></div></div></> }

function SettingsView({ dark,setDark,exportData,importClick,clear }: {dark:boolean;setDark:(v:boolean)=>void;exportData:()=>void;importClick:()=>void;clear:()=>void}) { return <><Header eyebrow="환경 설정" title="설정"/><div className="space-y-3 px-5"><Setting icon={dark?<Moon/>:<Sun/>} title="다크 모드" desc="어두운 화면으로 눈의 피로를 줄여요" right={<button onClick={()=>setDark(!dark)} className={`h-7 w-12 rounded-full p-1 transition ${dark?'bg-[#7057e8]':'bg-gray-200'}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${dark?'translate-x-5':''}`}/></button>}/><Setting icon={<Download/>} title="데이터 내보내기" desc="모든 기록을 JSON으로 백업해요" onClick={exportData}/><Setting icon={<Upload/>} title="데이터 불러오기" desc="백업 파일로 기록을 복원해요" onClick={importClick}/><Setting icon={<Trash2/>} title="전체 데이터 초기화" desc="저장된 모든 기록을 삭제해요" onClick={clear} danger/><div className="pt-8 text-center text-xs leading-5 text-gray-400">할부 기록장 1.0.0<br/>데이터는 이 기기의 브라우저에만 저장됩니다.</div></div></> }
function Setting({icon,title,desc,right,onClick,danger}:{icon:React.ReactNode;title:string;desc:string;right?:React.ReactNode;onClick?:()=>void;danger?:boolean}) { return <button onClick={onClick} className="flex min-h-[76px] w-full items-center gap-3 rounded-[20px] bg-white p-4 text-left dark:bg-[#211f29]"><span className={`grid h-10 w-10 place-items-center rounded-xl ${danger?'bg-red-50 text-red-500 dark:bg-red-500/10':'bg-violet-50 text-[#7057e8] dark:bg-violet-500/10'}`}>{icon}</span><span className="min-w-0 flex-1"><b className={danger?'text-red-500':''}>{title}</b><span className="mt-1 block text-xs text-gray-400">{desc}</span></span>{right||<ChevronRight size={18} className="text-gray-300"/>}</button> }

function Nav({tab,setTab,onAdd}:{tab:Tab;setTab:(t:Tab)=>void;onAdd:()=>void}) { const nav=[['home','홈',Home],['list','할부',List],['add','추가',CirclePlus],['stats','통계',BarChart3],['settings','설정',Settings]] as const; return <nav className="fixed bottom-0 left-1/2 z-30 flex h-[76px] w-full max-w-[480px] -translate-x-1/2 items-center justify-around border-t border-gray-100 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] backdrop-blur dark:border-white/5 dark:bg-[#211f29]/95">{nav.map(([key,label,Icon])=><button key={key} onClick={()=>key==='add'?onAdd():setTab(key)} className={`flex h-14 min-w-[56px] flex-col items-center justify-center gap-1 text-[10px] font-bold ${key==='add'?'-mt-8':tab===key?'text-[#7057e8]':'text-gray-400'}`}>{key==='add'?<span className="grid h-14 w-14 place-items-center rounded-full border-4 border-[#f8f7fb] bg-[#7057e8] text-white shadow-lg dark:border-[#15141b]"><Icon size={27}/></span>:<><Icon size={21}/><span>{label}</span></>}</button>)}</nav> }

function ModalShell({children,onClose}:{children:React.ReactNode;onClose:()=>void}) { return <div className="fixed inset-0 z-50 bg-black/35 backdrop-blur-sm"><div className="absolute inset-x-0 bottom-0 mx-auto max-h-[94vh] max-w-[480px] overflow-y-auto rounded-t-[30px] bg-[#f8f7fb] dark:bg-[#15141b]"><button onClick={onClose} aria-label="닫기" className="absolute right-5 top-5 z-10 grid h-10 w-10 place-items-center rounded-full bg-white shadow-sm dark:bg-[#292731]"><X size={19}/></button>{children}</div></div> }
function FormModal({form,setForm,onClose,onSave,editing}:{form:ItemFormData;setForm:(f:ItemFormData)=>void;onClose:()=>void;onSave:(e:React.FormEvent)=>void;editing:boolean}) { const field=(key:keyof ItemFormData,value:string)=>setForm({...form,[key]:value}); return <ModalShell onClose={onClose}><form onSubmit={onSave} className="px-5 pb-8 pt-7"><p className="text-sm font-bold text-[#7057e8]">{editing?'정보 변경':'새로운 기록'}</p><h2 className="mt-1 text-2xl font-extrabold">{editing?'할부 수정':'할부 등록'}</h2><div className="mt-6 space-y-4"><Input label="품목명 *" value={form.title} onChange={v=>field('title',v)} placeholder="예: 노트북" required/><Input label="총 결제 금액 *" type="number" value={form.totalAmount} onChange={v=>field('totalAmount',v)} placeholder="0" required/><div><label className="mb-2 block text-sm font-bold">할부 개월 수 *</label><div className="mb-2 flex gap-2 overflow-x-auto">{['3','6','12','24','36'].map(v=><button type="button" key={v} onClick={()=>field('installmentMonths',v)} className={`min-h-10 min-w-14 rounded-xl text-sm font-bold ${form.installmentMonths===v?'bg-[#7057e8] text-white':'bg-white dark:bg-[#211f29]'}`}>{v}개월</button>)}</div><input type="number" min="1" max="120" value={form.installmentMonths} onChange={e=>field('installmentMonths',e.target.value)} className="h-12 w-full rounded-2xl border-0 bg-white px-4 outline-none focus:ring-2 focus:ring-[#7057e8] dark:bg-[#211f29]" required/></div><Input label="첫 결제일 *" type="date" value={form.firstPaymentDate} onChange={v=>field('firstPaymentDate',v)} required/><Input label="이미 납부한 회차" type="number" value={form.paidCount} onChange={v=>field('paidCount',v)} min="0"/><Input label="카드사 또는 결제수단" value={form.paymentMethod} onChange={v=>field('paymentMethod',v)} placeholder="예: 삼성카드"/><Input label="구매처" value={form.merchant} onChange={v=>field('merchant',v)} placeholder="예: 공식 온라인몰"/><div><label className="mb-2 block text-sm font-bold">카테고리</label><select value={form.category} onChange={e=>field('category',e.target.value)} className="h-12 w-full rounded-2xl border-0 bg-white px-4 outline-none dark:bg-[#211f29]">{categories.map(c=><option key={c}>{c}</option>)}</select></div><div><label className="mb-2 block text-sm font-bold">메모</label><textarea value={form.memo} onChange={e=>field('memo',e.target.value)} rows={3} className="w-full resize-none rounded-2xl border-0 bg-white p-4 outline-none focus:ring-2 focus:ring-[#7057e8] dark:bg-[#211f29]" placeholder="기억할 내용을 적어두세요"/></div></div><button className="mt-6 h-14 w-full rounded-2xl bg-[#7057e8] font-extrabold text-white shadow-lg shadow-violet-200 dark:shadow-none">{editing?'수정 내용 저장':'할부 등록하기'}</button></form></ModalShell> }
function Input({label,value,onChange,type='text',placeholder,required,min}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;required?:boolean;min?:string}) { return <div><label className="mb-2 block text-sm font-bold">{label}</label><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required} min={min} className="h-12 w-full rounded-2xl border-0 bg-white px-4 outline-none focus:ring-2 focus:ring-[#7057e8] dark:bg-[#211f29]"/></div> }

function DetailModal({item,onClose,onEdit,onPay,onUndo,onDelete}:{item:InstallmentItem;onClose:()=>void;onEdit:()=>void;onPay:()=>void;onUndo:()=>void;onDelete:()=>void}) { const next=nextPayment(item); return <ModalShell onClose={onClose}><div className="px-5 pb-8 pt-7"><p className="text-sm font-bold text-[#7057e8]">{item.status==='active'?'진행 중':'납부 완료'}</p><h2 className="mt-1 pr-12 text-2xl font-extrabold">{item.title}</h2><p className="mt-1 text-sm text-gray-400">{item.paymentMethod || item.category}</p><div className="mt-5 rounded-[24px] bg-[#211f2d] p-5 text-white dark:bg-[#292731]"><p className="text-xs text-white/60">남은 할부 금액</p><p className="mt-1 text-2xl font-extrabold">{formatWon(remainingAmount(item))}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#9c86ff]" style={{width:`${progress(item)}%`}}/></div><div className="mt-2 flex justify-between text-xs text-white/60"><span>{item.paidCount}회 납부</span><span>{progress(item)}%</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Summary icon={<CalendarDays size={19}/>} label="다음 결제일" value={next?localDate(next.scheduledDate):'완료'} /><Summary icon={<CreditCard size={19}/>} label="월 납부 금액" value={formatWon(next?.amount || item.payments.at(-1)?.amount || 0)} /></div><div className="mt-6 flex gap-2">{item.status==='active'&&<button onClick={onPay} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-[#7057e8] font-bold text-white"><Check size={18}/>이번 회차 납부</button>}<button onClick={onEdit} className="grid h-12 w-12 place-items-center rounded-2xl bg-white dark:bg-[#211f29]"><Pencil size={18}/></button></div>{item.paidCount>0&&<button onClick={onUndo} className="mt-2 h-11 w-full text-sm font-bold text-gray-400">이전 납부 취소</button>}<h3 className="mt-7 font-extrabold">회차별 납부 내역</h3><div className="mt-3 overflow-hidden rounded-[20px] bg-white dark:bg-[#211f29]">{item.payments.map(p=><div key={p.id} className="flex min-h-14 items-center border-b border-gray-100 px-4 last:border-0 dark:border-white/5"><span className={`mr-3 grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${p.status==='paid'?'bg-green-100 text-green-600 dark:bg-green-500/15':'bg-gray-100 text-gray-400 dark:bg-white/10'}`}>{p.status==='paid'?<Check size={14}/>:p.sequence}</span><div className="flex-1"><p className="text-sm font-bold">{p.sequence}회차</p><p className="text-xs text-gray-400">{p.scheduledDate.replaceAll('-','.')}</p></div><div className="text-right"><p className="text-sm font-bold">{formatWon(p.amount)}</p><p className={`text-[11px] ${p.status==='paid'?'text-green-500':'text-gray-400'}`}>{p.status==='paid'?'납부 완료':'납부 예정'}</p></div></div>)}</div><button onClick={onDelete} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-2xl text-sm font-bold text-red-500"><Trash2 size={17}/>이 내역 삭제</button></div></ModalShell> }
